# Generated by Django 3.2.4 on 2021-06-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('year', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=1024)),
                ('awards', models.CharField(max_length=10)),
                ('nominations', models.CharField(max_length=10)),
            ],
        ),
    ]
