# Generated by Django 3.2.4 on 2021-06-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestmovies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
